sudo: required
services:
        - docker

before_install:
        - docker build -t rodolfomansur/docker-react -f Dockerfile.dev .

script:
        - docker run rodolfomansur/docker-react npm run test -- --coverage
